---
# all, none, or list of linter keys
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - apm_modules
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_DEFAULT_STYLE: rumdl
PYTHON_DEFAULT_STYLE: ruff
SHOW_ELAPSED_TIME: true
TYPESCRIPT_DEFAULT_STYLE: prettier
