[MD007]
indent = 2
style = "fixed"

[MD013]
line-length = 400

[MD024]
siblings-only = true

[MD026]
punctuation = ".,;:!。，；:"

[global]
disable = ["MD029", "MD033", "MD036", "MD004"]
exclude = ["**/.agents/skills/**"]
