# :schema https://gist.githubusercontent.com/MRDGH2821/d61a45f6d91c94d1c9d3d1307036d361/raw/fe5c99a3237fa12ee6e0c247999832857d97d353/treefmt-schema.json

allow-missing-formatter = true
excludes = ["package-lock.json"]

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]
options = ["-q"]
priority = 10

[formatter.cspell-sort]
command = "yq"
# tombi: format.rules.array-values-order = "ascending"
includes = [
  "**/.cSpell*",
  "**/.cspell*",
  "**/cSpell*",
  "**/cspell*",
  ".cSpell*",
  ".cspell*",
  "cSpell*",
  "cspell*"
]
no-positional-arg-support = true
options = ["-i", ".words|= sort_by(downcase)|.ignorePaths|=sort_by(downcase)"]
priority = 9

[formatter.ignore-files-formatter]
command = "uvx"
# tombi: format.rules.array-values-order = "ascending"
includes = ["**/.*ignore", ".*ignore"]
options = ["git+https://github.com/lorenzwalthert/gitignore-tidy"]
priority = 1

[formatter.keep-sorted]
command = "keep-sorted"
includes = ["*"]
priority = 10

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
priority = 1

[formatter.pkl]
command = "pkl"
includes = ["*.pkl"]
options = ["format", "-w", "."]

[formatter.prettier]
command = "bunx"
# tombi: format.rules.array-values-order = "ascending"
excludes = [
  "*.*ignore",
  "*.aac",
  "*.docx",
  "*.gitkeep",
  "*.jinja",
  "*.jpg",
  "*.lock",
  "*.lock.*",
  "*.lock.yaml",
  "*.mp4",
  "*.nix",
  "*.pdf",
  "*.pkl",
  "*.png",
  "*.pptx",
  "*.py",
  "*.txt",
  "*.typ",
  "LICENCE",
  "LICENSE",
  "apm.lock.yaml",
  "justfile",
  "package-lock.json"
]
includes = ["*"]
options = ["prettier", "--log-level", "error", "--write"]
priority = 100

[formatter.prettypst-default]
command = "prettypst"
includes = ["*.typ"]
no-positional-arg-support = true
options = ["-s", "default"]
priority = 2

[formatter.prettypst-otbs]
command = "prettypst"
includes = ["*.typ"]
no-positional-arg-support = true
options = ["-s", "otbs"]
priority = 3

[formatter.ruff-format]
command = "uvx"
excludes = []
includes = ["*.py"]
options = ["ruff", "format"]
priority = 9

[formatter.ruff-lint]
command = "uvx"
excludes = []
includes = ["*.py"]
options = ["ruff", "check", "--fix"]
priority = 8

[formatter.sort-markdown-tables]
command = "smt"
includes = ["*.md"]
options = ["-i"]
priority = 2

[formatter.sort-package-json]
command = "bunx"
includes = ["package.json"]
options = ["sort-package-json"]
priority = 10

[formatter.tombi-format]
command = "uvx"
includes = ["*.toml"]
options = ["tombi", "format"]
priority = 11

[formatter.toml-sort]
command = "uvx"
includes = ["*.toml"]
options = ["toml-sort", "-i", "--sort-table-keys", "--sort-inline-tables"]
priority = 0

[formatter.typstyle]
command = "typstyle"
includes = ["*.typ"]
options = ["-i"]
priority = 1

[formatter.yamlfix]
command = "uvx"
# tombi: format.rules.array-values-order = "ascending"
includes = ["*.yaml", "*.yml"]
options = ["yamlfix"]
priority = 8

[formatter.yq-key-sort]
command = "yq"
# tombi: format.rules.array-values-order = "ascending"
includes = ["*.json", "*.yaml", "*.yml"]
no-positional-arg-support = true
options = ["-i", "-P", "sort_keys(..)"]
priority = 0
