apply plugin: 'com.android.library'

group = 'expo.modules.volumefire'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.volumefire"
  compileSdkVersion 36
  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36
  }
}
