[files]
yaml = ["*.yaml", "*.yml", ".yamllint"]

[rules]
anchors = "enable"
brackets = "enable"
colons = "enable"
commas = "enable"
document-end = "disable"
empty-lines = "enable"
empty-values = "disable"
float-values = "disable"
hyphens = "enable"
indentation = "enable"
key-duplicates = "enable"
key-ordering = "disable"
new-line-at-end-of-file = "enable"
octal-values = "disable"
trailing-spaces = "enable"

[rules.braces]
max-spaces-inside = 1

[rules.comments]
level = "warning"
min-spaces-from-content = 1

[rules.comments-indentation]
level = "warning"

[rules.document-start]
level = "warning"

[rules.line-length]
max = 500

[rules.new-lines]
level = "warning"
type = "unix"

[rules.quoted-strings]
allow-quoted-quotes = true
quote-type = "double"
required = false

[rules.truthy]
level = "warning"
