---
name: React Native CI
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - dev
      - main
jobs:
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: TypeScript check
        run: npx tsc --noEmit
